apiVersion: argopry.io/v1alpha1
kind: Application
metadata:
  name: eksapp
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/davidolufemi/eks-aws-app.git
    targetRevision: HEAD
    path: .
  
  destination:
    server: https://kubernetes.default.svc
    namespace: eksappns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true